# Shared by the application and the standalone Windows portable launcher.
option(VIDEO_PLAYER_OPTIMIZE_SIZE "Enable LTO and size optimizations in release builds" ON)
if(VIDEO_PLAYER_OPTIMIZE_SIZE)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT ipo_supported OUTPUT ipo_error LANGUAGES CXX)
    if(NOT ipo_supported)
        message(FATAL_ERROR "Release LTO is unavailable: ${ipo_error}")
    endif()
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_MINSIZEREL ON)

    # Replace the default speed optimization rather than pass conflicting flags.
    foreach(config RELEASE MINSIZEREL)
        if(MSVC)
            string(REGEX REPLACE "(^| )/O[12sx]( |$)" " " CMAKE_CXX_FLAGS_${config} "${CMAKE_CXX_FLAGS_${config}}")
            string(APPEND CMAKE_CXX_FLAGS_${config} " /O1 /Gy /Gw")
        else()
            string(REGEX REPLACE "(^| )-O[0123sz]( |$)" " " CMAKE_CXX_FLAGS_${config} "${CMAKE_CXX_FLAGS_${config}}")
            string(APPEND CMAKE_CXX_FLAGS_${config} " -Os -ffunction-sections -fdata-sections")
        endif()
    endforeach()

    if(MSVC)
        add_link_options("$<$<CONFIG:Release,MinSizeRel>:/OPT:REF;/OPT:ICF>")
    elseif(APPLE)
        add_link_options("$<$<CONFIG:Release,MinSizeRel>:-Wl,-dead_strip>")
    else()
        add_link_options("$<$<CONFIG:Release,MinSizeRel>:-Wl,--gc-sections;-s>")
    endif()
endif()
